$axure.loadCurrentPage({
  "url":"态势首页.html",
  "generationDate":new Date(1495879054053.62),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"7108ab9f6f314a76ac30bbff5c94955e",
    "type":"Axure:Page",
    "name":"态势首页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFF333333},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"efa1dcbbb13741bfbe1441f6a8557010",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF5F5F5},
            "location":{
              "x":125,
              "y":90},
            "size":{
              "width":375,
              "height":692}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"56809815d7714d27800f288112ea3580",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF5F5F5},
                "location":{
                  "x":125,
                  "y":90},
                "size":{
                  "width":375,
                  "height":692}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/态势首页/u0.png"}},
{
          "id":"2e49ffa5f1814c7887fc3d97cc5cbe21",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF473E69},
            "location":{
              "x":125,
              "y":90},
            "size":{
              "width":375,
              "height":20},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f87053d6b12540eea34bf2bae12435ef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF473E69},
                "location":{
                  "x":125,
                  "y":90},
                "size":{
                  "width":375,
                  "height":20},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/统计页/u2.png"}},
{
          "id":"4351bed3841c4797938fd3c6dbb0f891",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":129,
              "y":92},
            "size":{
              "width":365,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"469a780553c245638805be4e048e6a7d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":129,
                  "y":92},
                "size":{
                  "width":365,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/统计页/u4.png"}},
{
          "id":"01b0a50a42a2400a9d717a46489b3e29",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF473E69},
            "location":{
              "x":125,
              "y":108},
            "size":{
              "width":375,
              "height":44},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b734b3e475dc4654a4ebb194454102ac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF473E69},
                "location":{
                  "x":125,
                  "y":108},
                "size":{
                  "width":375,
                  "height":44},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/态势首页/u6.png"}},
{
          "id":"e71cc25bc5104dfb86aadc06a22400ed",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":135,
              "y":122},
            "size":{
              "width":10,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef03e24e127642b8a4acdf4f0b7b0346",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":135,
                  "y":122},
                "size":{
                  "width":10,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/统计页/u8.png"}},
{
          "id":"f806c0ad0a994d26b6efbf4cf81161be",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF473E69},
            "location":{
              "x":293,
              "y":120},
            "size":{
              "width":37,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"982d170cef2a40a8b1b9f7784fcb4b36",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF473E69},
                "location":{
                  "x":293,
                  "y":120},
                "size":{
                  "width":37,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/态势首页/u10.png"}},
{
          "id":"15fcdbc38d64497a81e0e5c9a3475bc9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":126,
              "y":318},
            "size":{
              "width":374,
              "height":81},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1e33190a7c5043fa8120c3b7331e82d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":126,
                  "y":318},
                "size":{
                  "width":374,
                  "height":81},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/态势首页/u12.png"}},
{
          "id":"7524544b7f434525a4e2799aca2450b6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":125,
              "y":152},
            "size":{
              "width":375,
              "height":167}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ca7e3ff3fd824947a406ef1c562462d5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":125,
                  "y":152},
                "size":{
                  "width":375,
                  "height":167}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/态势首页/u14.jpg"}},
{
          "id":"d8191558b95e4a908aef797f23f35e28",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":306,
              "y":326},
            "size":{
              "width":10,
              "height":64},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/态势首页/u16_line.png"}},
{
          "id":"42b062ef4df94f5b9ce1251ff1fe56c1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":143,
              "y":343},
            "size":{
              "width":46,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ae40731c9675457dbdb2c22b0124a8b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":143,
                  "y":343},
                "size":{
                  "width":46,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/态势首页/u17.png"}},
{
          "id":"a63fa98a8560459db502694c18084edf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":196,
              "y":341},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"24ffd6ddaac84b7a912a27eae625936d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":196,
                  "y":341},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0a4aafbbc52e447eb655314aa0f3a352",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":333,
              "y":339},
            "size":{
              "width":46,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6d4e3d8cc02f4e41889c6f87f726181a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":333,
                  "y":339},
                "size":{
                  "width":46,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/态势首页/u21.png"}},
{
          "id":"0c5a4ce3978940c59de589b8fd5c3b9e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":387,
              "y":340},
            "size":{
              "width":68,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7ac8c19ccc454d1da14ec8894efe38d1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":387,
                  "y":340},
                "size":{
                  "width":68,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"979b5b57069844a8a46c17b5528a9f2d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":196,
              "y":366},
            "size":{
              "width":100,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9b127f1e3cda4e7688cc23801eef4894",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":196,
                  "y":366},
                "size":{
                  "width":100,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"22996fe0d8214bbc9170b59dc41dbe21",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":387,
              "y":366},
            "size":{
              "width":100,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"633e0d64948e4c0d90a59b1fc83331b5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":387,
                  "y":366},
                "size":{
                  "width":100,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "efa1dcbbb13741bfbe1441f6a8557010":{
      "scriptId":"u0"},
    "56809815d7714d27800f288112ea3580":{
      "scriptId":"u1"},
    "2e49ffa5f1814c7887fc3d97cc5cbe21":{
      "scriptId":"u2"},
    "f87053d6b12540eea34bf2bae12435ef":{
      "scriptId":"u3"},
    "4351bed3841c4797938fd3c6dbb0f891":{
      "scriptId":"u4"},
    "469a780553c245638805be4e048e6a7d":{
      "scriptId":"u5"},
    "01b0a50a42a2400a9d717a46489b3e29":{
      "scriptId":"u6"},
    "b734b3e475dc4654a4ebb194454102ac":{
      "scriptId":"u7"},
    "e71cc25bc5104dfb86aadc06a22400ed":{
      "scriptId":"u8"},
    "ef03e24e127642b8a4acdf4f0b7b0346":{
      "scriptId":"u9"},
    "f806c0ad0a994d26b6efbf4cf81161be":{
      "scriptId":"u10"},
    "982d170cef2a40a8b1b9f7784fcb4b36":{
      "scriptId":"u11"},
    "15fcdbc38d64497a81e0e5c9a3475bc9":{
      "scriptId":"u12"},
    "1e33190a7c5043fa8120c3b7331e82d9":{
      "scriptId":"u13"},
    "7524544b7f434525a4e2799aca2450b6":{
      "scriptId":"u14"},
    "ca7e3ff3fd824947a406ef1c562462d5":{
      "scriptId":"u15"},
    "d8191558b95e4a908aef797f23f35e28":{
      "scriptId":"u16"},
    "42b062ef4df94f5b9ce1251ff1fe56c1":{
      "scriptId":"u17"},
    "ae40731c9675457dbdb2c22b0124a8b9":{
      "scriptId":"u18"},
    "a63fa98a8560459db502694c18084edf":{
      "scriptId":"u19"},
    "24ffd6ddaac84b7a912a27eae625936d":{
      "scriptId":"u20"},
    "0a4aafbbc52e447eb655314aa0f3a352":{
      "scriptId":"u21"},
    "6d4e3d8cc02f4e41889c6f87f726181a":{
      "scriptId":"u22"},
    "0c5a4ce3978940c59de589b8fd5c3b9e":{
      "scriptId":"u23"},
    "7ac8c19ccc454d1da14ec8894efe38d1":{
      "scriptId":"u24"},
    "979b5b57069844a8a46c17b5528a9f2d":{
      "scriptId":"u25"},
    "9b127f1e3cda4e7688cc23801eef4894":{
      "scriptId":"u26"},
    "22996fe0d8214bbc9170b59dc41dbe21":{
      "scriptId":"u27"},
    "633e0d64948e4c0d90a59b1fc83331b5":{
      "scriptId":"u28"}}});